spring:
datasource:
url: jdbc:h2:mem:lms
driverClassName: org.h2.Driver
username: sa
password:

jpa:
hibernate:
ddl-auto: validate

liquibase:
change-log: classpath:db/changelog/db.changelog-master.yaml



springdoc.model-and-view-parameters-as-fields=true

management.endpoints.web.exposure.include=health,info,loggers

management.endpoint.health.show-details=always

logging.level.root=INFO

logging.level.com.practice.lms=DEBUG

logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.orm.results=TRACE