databaseChangeLog:
  - changeSet:
      id: 003-create-course-settings
      author: arseniy.bsuir@gmail.com
      changes:
        - createTable:
            tableName: course_settings
            columns:
              - column:
                  name: id
                  type: UUID
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: course_id
                  type: UUID
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: start_date
                  type: TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: end_date
                  type: TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: is_public
                  type: BOOLEAN
                  defaultValueBoolean: false
                  constraints:
                    nullable: false
        - addForeignKeyConstraint:
            constraintName: fk_course_settings_course
            baseTableName: course_settings
            baseColumnNames: course_id
            referencedTableName: courses
            referencedColumnNames: id
            onDelete: CASCADE