databaseChangeLog:
  - changeSet:
      id: 004-create-course-settings
      author: me
      changes:
        - createTable:
            tableName: course_settings
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true

              - column:
                  name: course_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    unique: true

              - column:
                  name: difficulty
                  type: VARCHAR(255)

              - column:
                  name: duration
                  type: INT

              - column:
                  name: is_public
                  type: BOOLEAN